config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get '/validators/uniqueness/group/', to: 'validators/uniqueness#group'
  get '/validators/uniqueness/user/', to: 'validators/uniqueness#user'
  get '/validators/uniqueness/proposal/', to: 'validators/uniqueness#proposal'

  resources :searches, only: [:index]

  resources :sys_payment_notifications, only: [:create]

  resources :user_likes, only: %i[create destroy]

  resources :proposal_nicknames, only: [:update]

  mount Ckeditor::Engine => '/ckeditor'

  get 'home' => 'home#show'
  get 'landing' => 'home#landing'
  get 'public' => 'home#public', as: :open_space
  get 'edemocracy' => 'home#intro'
  get 'eparticipation' => 'home#intro'
  get 'press' => 'home#press'
  get 'privacy' => 'home#privacy'
  get 'terms' => 'home#terms'
  get 'cookie_law' => 'home#cookie_law'
  post 'send_feedback' => 'home#feedback'
  get 'statistics' => 'home#statistics'
  get 'school' => 'home#school'
  get 'municipality' => 'home#municipality'

  resources :quorums do
    collection do
      get :dates
      get :help
    end
  end

  resources :best_quorums, controller: 'quorums'
  resources :old_quorums, controller: 'quorums'

  resources :proposals do
    collection do
      get :endless_index
      get :similar
      get :tab_list
    end

    resources :proposal_comments do
      member do
        put :rankup
        put :ranknil
        put :rankdown
        get :show_all_replies
        put :unintegrate
        get :history
      end
      collection do
        post :mark_noise
        get :list
        get :left_list
        get :edit_list
        post :report
        get :noise
        get :manage_noise
      end
    end

    resources :proposal_revisions
    resources :proposal_lives
    resources :proposal_supports
    resources :proposal_presentations

    resources :blocked_proposal_alerts do
      collection do
        post :block
        post :unlock
      end
    end

    member do
      get :rankup
      get :rankdown
      patch :set_votation_date
      post :available_author
      get :available_authors_list
      put :add_authors
      get :vote_results
      post :close_debate
      post :start_votation
      patch :regenerate
      get :geocode
      get :promote
      get :banner
      get :test_banner
    end
  end

  resources :proposal_categories, only: [:index]

  resources :announcements, only: [] do
    post :hide, on: :member
  end

  resources :tutorials, only: [] do
    resources :steps, only: [] do
      member do
        get :complete
      end
    end
  end

  resources :alerts do
    member do
      get :check
      get :check_alert # TODO: remove in one year from 08-05-2014
    end

    collection do
      get :proposal
      post :check_all
    end
  end

  resources :interest_borders
  resources :municipalities

  get 'elfinder' => 'elfinder#elfinder'
  post 'elfinder' => 'elfinder#elfinder'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'sessions', registrations: 'registrations', passwords: 'passwords', confirmations: 'confirmations' } do
    get '/users/sign_in', to: 'devise/sessions#new'
    get '/users/sign_out', to: 'devise/sessions#destroy'
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  resources :users do
    collection do
      get :confirm_credentials
      get :alarm_preferences
      get :border_preferences
      post :join_accounts
      get :privacy_preferences
      get :statistics
      post :change_show_tooltips
      post :change_show_urls
      post :change_receive_messages
      post :change_rotp_enabled
      post :change_locale
      post :change_time_zone
    end

    member do
      get :show_message
      post :send_message
    end

    resources :authentications
  end

  resources :notifications do
    collection do
      post :change_notification_block
      post :change_email_notification_block
      post :change_email_block
    end
  end

  concern :blog_posts do
    resources :blog_posts do
      get :drafts, on: :collection
      resources :blog_comments
    end
  end

  concerns :blog_posts

  resources :blogs do
    concerns :blog_posts
    get '/:year/:month' => 'blogs#by_year_and_month', as: :posts_by_year_and_month, on: :member
  end

  resources :tags

  get '/tags/:text', to: 'tags#show'

  get '/votation/', to: 'votations#show'
  put '/votation/vote', to: 'votations#vote'
  put '/votation/vote_schulze', to: 'votations#vote_schulze'
  resources :votations

  concern :group_invitations do
    resources :group_invitations do
      resources :group_invitation_emails, param: :token do
        member do
          get :accept
          get :reject
          get :anymore
        end
      end
    end
  end

  concern :eventable do
    resources :events do
      resources :meeting_participations, only: [:create]

      resources :event_comments do
        member do
          post :like
        end
      end
      member do
        post :move
        post :resize
      end
      collection do
        get :list
      end
    end
  end

  concern :participation_roles do
    resources :participation_roles do
      collection do
        post :change_default_role
      end
    end
  end

  concerns :eventable

  root to: 'home#index'
  namespace :api do
    namespace :v1 do
      resources :proposals, only: %i[show index]
      devise_scope :user do
        post 'login' => 'sessions#create', as: :login
      end
    end
  end

  resources :proposal_categories do
    get :index, scope: :collection
  end

  resources :groups do
    member do
      post :ask_for_participation
      put :participation_request_confirm
      put :participation_request_decline
      post :create_event
      post :change_default_anonima
      post :change_default_visible_outside
      post :change_advanced_options
      post :change_default_secret_vote
      get :reload_storage_size
      put :enable_areas
      put :remove_post
      put :feature_post
      get :permissions_list
    end

    collection do
      post :ask_for_multiple_follow
      get :autocomplete
    end

    resources :forums, controller: 'frm/forums', only: %i[index show] do
      resources :topics, controller: 'frm/topics' do
        member do
          get :subscribe
          get :unsubscribe
        end
      end

      resources :topics, controller: 'frm/topics', only: %i[new create index show destroy] do
        resources :posts, controller: 'frm/posts'
      end
    end

    namespace :frm do
      get 'forums/:forum_id/moderation', to: 'moderation#index', as: :forum_moderator_tools
      # For mass moderation of posts
      put 'forums/:forum_id/moderate/posts', to: 'moderation#posts', as: :forum_moderate_posts
      # Moderation of a single topic
      put 'forums/:forum_id/topics/:topic_id/moderate', to: 'moderation#topic', as: :moderate_forum_topic
      resources :categories, only: %i[index show]
      namespace :admin do
        root to: 'base#index'
        resources :mods do
          resources :members do
            collection do
              post :add
            end
          end
        end

        resources :forums do
          resources :moderators
          resources :topics do
            member do
              put :toggle_hide
              put :toggle_lock
              put :toggle_pin
            end
          end
        end

        resources :categories
      end
    end

    get 'users/autocomplete', to: 'users#autocomplete', as: 'user_autocomplete'

    concerns :eventable

    concerns :group_invitations

    resources :elections

    resources :candidates

    resources :group_participations do
      collection do
        post :send_email
        post :destroy_all
      end
      member do
        post :change_user_permission
      end
    end

    concerns :participation_roles

    resources :search_participants

    resources :proposals do
      collection do
        get :search
      end
      member do
        post :close_debate
        post :start_votation
        patch :regenerate
        patch :set_votation_date
        get :geocode
        get :vote_results
      end
    end

    resources :quorums do
      member do
        post :change_status
      end
    end

    resources :best_quorums, controller: 'quorums'
    resources :old_quorums, controller: 'quorums'

    resources :documents do
      collection do
        get :view
      end
    end

    resources :group_areas do
      resources :area_roles do
        member do
          patch :change
        end
        collection do
          put :change_permissions
        end
      end

      resources :area_participations, only: %i[create update destroy]
    end

    concerns :blog_posts

    get '/:year/:month' => 'groups#by_year_and_month', :as => :posts_by_year_and_month, on: :member
  end

  resources :documents do
    collection do
      get :view
      get :download
    end
    member do
    end
  end

  admin_required = lambda do |request|
    request.env['warden'].authenticate? && request.env['warden'].user.admin?
  end

  moderator_required = lambda do |request|
    request.env['warden'].authenticate? && request.env['warden'].user.moderator?
  end

  constraints moderator_required do
    get 'moderator_panel', to: 'admin/moderator#show', as: 'moderator/panel'
  end

  constraints admin_required do
    namespace :admin do
      resources :newsletters do
        member do
          get :preview
          patch :publish
        end
      end
      mount RailsAdmin::Engine => '/data', as: 'rails_admin'
      mount Sidekiq::Web => '/sidekiq'
      get '/', to: 'panel#show', as: 'panel'
      resource :panel, controller: 'panel' do
        get :calculate_rankings
        get :change_proposals_state
        get :write_sitemap
        get :delete_old_notifications
        get :test_redis
        get :test_scheduler
        get :test_exceptions
        get :calculate_user_group_affinity

app/views/proposal_types/_agenda_solution.html.erb
<%
   seq = 0
   solution = Solution.new
   solution.sections.build(title: t('pages.proposals.new.agenda.solution.title'), seq: seq+=1).paragraphs.build(content: '', seq: 1)
   solution.sections.build(title: 'Importo', seq: seq+=1).paragraphs.build(content: '', seq: 1)
   solution.sections.build(title: 'Rispetto dei vincoli e problemi', seq: seq+=1).paragraphs.build(content: '', seq: 1)
   solution.sections.build(title: 'Documentazione', seq: seq+=1).paragraphs.build(content: '', seq: 1)
%>


<div class="solution_main">
  <h3>
    <div class="tit1 sol">
      <div class="tit2">
        <%= "Soluzione #{solution.seq}" %>
      </div>
    </div>
  </h3>
  <div class="sol_content">
    <div class="solutions_column">
      <%= fields_for :proposals, Proposal.new do |p| %>
          <%= p.fields_for :solutions, solution do |sol| %>
              <%= sol.hidden_field :seq %>
              <%= sol.check_box '_destroy', style: 'display:none' %>
              <% solution.sections.each do |section| %>
                  <%= sol.fields_for :sections, section do |s| %>
                      <%= s.hidden_field :title %>
                      <%= s.hidden_field :seq %>
                      <%= s.fields_for :paragraphs, section.paragraphs.first do |p| %>
                          <p class="section_container">
                            <%= s.text_field :title, class: "edit_label" %>
                            <span class="move_button">
                              <%= image_tag 'move.png' %>
                            </span>
                             <span class="remove_button">
                              <a href="#" onclick="removeSolution(this,0,true);return false;"><%= 'Rimuovi sezione' %></a>
                            </span>
                            <br/>
                            <%= p.text_area :content_dirty, :rows => 5, :style => "width:98%;height:280px;", :class => "tinymce" %>
                            <%= p.hidden_field :content %>
                            <%= p.hidden_field :seq %>
                          </p>
                      <% end %>
                  <% end %>
              <% end %>
          <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/proposal_types/_form.html.erb
<h2><%= @title %></h2>

<div id="create_proposal">
  <%= simple_form_for @group.present? ? [@group, @proposal] : @proposal, validate: true, remote: request.xhr? do |f| %>
    <div class="step root root">
      <div class="mb-2"><%= t('pages.proposals.new.step_1_title', app_short_name: APP_SHORT_NAME) %></div>

      <%= f.input :title,
                  label: t('pages.proposals.new.title_synthetic'),
                  placeholder: t('pages.proposals.new.title_placeholder'),
                  input_html: { autocomplete: :off, data: { fv_trigger: 'keyup' } } %>

      <% if @group && @group.enable_areas && @group.group_areas.any? %>
        <% available_areas = current_user.scoped_areas(@group, :insert_proposals) %>
        <p>
          <% if available_areas.any? %>
            <%= f.input :group_area_id, as: :select,
                        collection: available_areas.collect { |p| [p.name, p.id] },
                        prompt: t('pages.proposals.new.no_work_area_selected') %>
          <% else %>
            <%= t('pages.proposals.new.cannot_add_proposal_in_work_area') %>
          <% end %>
        </p>
      <% end %>
      <p>
        <%= f.input 'interest_borders_tkn', input_html: { "data-pre" => @proposal.interest_borders.to_json, placeholder: t('pages.proposals.new.interest_borders_tkn_placeholder'), style: "width:100%" } %>
      </p>
    </div>

    <div class="step">
      <% if ::Configuration.proposal_categories %>
        <div class="inputs">
          <%= f.label :proposal_category_id %>
          <%= f.select :proposal_category_id,
                       options_for_select(ProposalCategory.all.collect do |p|
                         [p.description, p.id, { 'data-imagesrc' => image_path("proposal_categories/#{p.name}_s.png") }]
                       end,
                                          @proposal.proposal_category_id),
                       { include_blank: t('pages.proposals.new.category_prompt') },
                       { required: true, style: 'width:100%' } %>
        </div>
      <% end %>

      <% if ::Configuration::folksonomy %>
        <p>
          <%= f.input :tags_list, input_html: { placeholder: t('pages.proposals.new.tags_list_placeholder'), style: "width:100%" } %>
        </p>
      <% end %>
    </div>

    <%= @proposal.sections.first.title %>
    <div class="step">
      <%= f.fields_for :sections, @proposal.sections.first do |s| %>
        <%= s.input :title, as: :hidden %>
        <%= s.input :seq, as: :hidden %>
        <%= s.fields_for :paragraphs, @proposal.sections.first.paragraphs.build(seq: 1) do |p| %>
          <p>
            <%= p.input :content, as: :text, label: @proposal.sections.first.question, input_html: { rows: 5 } %>
            <%= p.input :seq, as: :hidden %>
          </p>
        <% end %>
      <% end %>

<!--      <div class="suggestion_box">-->
        <%#= raw @proposal.sections.first.suggestion %>
<!--      </div>-->
    </div>

    <div class="step">
      <%= render partial: '/proposal_types/quorum_choice', locals: { f: f } %>
      <div class="suggestion_box">
        <%= t('pages.proposals.new.step_4_footer_html', app_short_name: APP_SHORT_NAME) %>
      </div>

      <% if @proposal.change_advanced_options %>
        <fieldset>
          <legend><%= t('pages.proposals.new.advanced_options') %></legend>
          <%= f.input :anonima %>
          <%= f.input :visible_outside %>
          <%= f.input :secret_vote %>
        </fieldset>
      <% end %>

      <p>
        <% if @group %>
          <input type="hidden" name="from_group" value="<%= @group.id %>"/>
        <% end %>
        <%= f.hidden_field :private %>
        <%= f.hidden_field :proposal_type_id %>
        <%= f.hidden_field :proposal_votation_type_id %>
        <%= f.hidden_field :topic_id %>
      </p>

      <p>
        <%= link_to t('buttons.cancel'), :back, class: 'btn' unless request.xhr? %>
        <%= f.submit t('pages.proposals.new.create_button'), class: 'btn blue disable', data: { disable_with: t('loading') } %>
      </p>
    </div>
  <% end %>
</div>

app/views/proposal_types/_petition.html.erb
<h2><%=@title%></h2>
<div id="create_proposal">
  <%= form_for (@group.present?) ? [@group, @proposal] : @proposal, validate: true, remote: true do |f| %>
      <% if request.xhr? %>
          <div class="legend first">
            <div class="number">1</div>
            <div class="title">
              <%= t('pages.proposals.new.step_base_info') %>
            </div>
          </div>
          <div class="legend first">
            <div class="number">2</div>
            <div class="title">
              <%= t('pages.proposals.new.step_classification') %>
            </div>
          </div>
          <div class="legend">
            <div class="number">3</div>
            <div class="title">
              <%= t('pages.proposals.new.step_similar') %>
            </div>
          </div>
          <div class="legend">
            <div class="number">4</div>
            <div class="title">
              <%= @problems.title %>
            </div>
          </div>
          <div class="legend last">
            <div class="number">5</div>
            <div class="title">
              <%= t('pages.proposals.new.signatures') %>
            </div>
          </div>
      <% else %>
          <%= render partial: 'fragments/error_messages', locals: {resource: @proposal} %>
      <% end %>

      <div class="step root root">
        <p>
          <%= f.label :title, t('pages.proposals.new.title_synthetic') %>
          <%= f.text_field :title, placeholder: t('pages.proposals.new.title_placeholder'), style: "width:500px" %>
        </p>


        <% @available_areas = current_user.scoped_areas(@group, :insert_proposals) %>
        <% if @group && @group.enable_areas && @group.group_areas.count > 0 && params[:action] == "new" %>
            <p>
              <%= f.label :group_area_id %>
              <% if @available_areas.size > 0 %>
                  <%= f.select :group_area_id, current_user.scoped_areas(@group, :insert_proposals).collect { |p| [p.name, p.id] }, {prompt: t('pages.proposals.new.no_work_area_selected')}, style: "width:500px" %>
              <% else %>
                  <%= t('pages.proposals.new.cannot_add_proposal_in_work_area') %>
              <% end %>
            </p>
        <% end %>

        <p>
          <%= f.label :interest_borders_tkn %>
          <%= f.text_field 'interest_borders_tkn', "data-pre" => @proposal.interest_borders.to_json , placeholder: t('pages.proposals.new.interest_borders_tkn_placeholder'), style: "width:500px" %>
        </p>

        <p>
          <% if @group %>
              <input type="hidden" name="from_group" value="<%= @group.id %>"/>
          <% end %>
          <%= f.hidden_field :private %>
          <%= f.hidden_field :proposal_type_id %>
          <%= f.hidden_field :proposal_votation_type_id %>
          <%= f.hidden_field :topic_id %>
        </p>
      </div>

      <div class="step">
        <% if ::Configuration.proposal_categories %>
            <p>
              <%= f.label :proposal_category_id %>
              <%= f.select :proposal_category_id, options_for_select(ProposalCategory.all.collect { |p| [p.description, p.id, {'data-imagesrc' => image_path("proposal_categories/#{p.name}_s.png")}]}, @proposal.proposal_category_id),{include_blank: t('pages.proposals.new.category_prompt')}, {style: 'width:500px'} %>
            </p>
        <% end %>

        <% if ::Configuration::folksonomy %>
            <p>
              <%= f.label :tags_list %>
              <%= f.text_field :tags_list, placeholder: t('pages.proposals.new.tags_list_placeholder'), style: "width:500px" %>
            </p>
        <% end %>


      </div>


      <div class="step" id="suggestions">
      </div>

      <div class="step">
        <%= f.fields_for :sections, @problems do |s| %>
            <%= s.hidden_field :title %>
            <%= s.hidden_field :seq %>
            <%= s.fields_for :paragraphs, @problems.paragraphs.build(seq: 1) do |p| %>
                <p>
                  <%= p.label :content, @problems.question %>
                  <%= p.cktext_area :content, rows: 5, style: "width:98%;", ckeditor: {toolbar: 'proposal', language: I18n.locale} %>
                  <%= p.hidden_field :seq %>
                </p>
            <% end %>
        <% end %>

        <div class="suggestion_box">
          <%= raw @problems.suggestion %>
        </div>

      </div>

      <div class="step">
        <%=f.label :signatures %>
        <%= f.text_field :signatures %>


        <%= f.radio_button :petition_phase, :signatures %><%= f.label :petition_phase, 'Collect signatures' %>
        <%= f.radio_button :petition_phase, :debate %><%= f.label :petition_phase, 'Debate and build' %>

      </div>

      <p>
        <%= link_to t('buttons.cancel'), :back, class: 'btn' unless request.xhr? %>
        <%= f.submit t('pages.proposals.new.create_button'), class: 'btn blue disable', data:{ disable_with: t('loading') } %>
      </p>
  <% end %>


  <script type="text/javascript">
      $(function() {
          var input = $('#proposal_interest_borders_tkn')
          input.tokenInput("<%=interest_borders_path(format: :json)%>", {
              propertyToSearch: 'text',
              crossDomain: false,
              prePopulate: input.data("pre"),
              hintText: "<%=t('interest_borders.hint')%>",
              noResultsText: "<%=t('interest_borders.no_place_found')%>",
              searchingText: "<%=t('interest_borders.searching')%>",
              preventDuplicates: true,
              allowTabOut: true
          });

          input = $('#proposal_tags_list')
          if (input != null) {
              input.tokenInput("<%=tags_path(format: :json )%>", {
                  theme: "facebook",
                  crossDomain: false,
                  allowFreeTagging: true,
                  minChars: 3,
                  hintText: "<%=t('digit_tags')%>",
                  searchingText: "<%=t('digit_tags')%>",
                  preventDuplicates: true,
                  allowTabOut: true,
                  tokenValue: "name"
              })
          }

          $('#proposal_proposal_category_id').select2({
              minimumResultsForSearch: -1,
              templateResult: formatCategory,
              templateSelection: formatCategory,
              escapeMarkup: function(m) { return m; }
          });
      });
  </script>
</div>
<a class="close-reveal-modal">&#215;</a>

app/views/proposal_types/_poll.html.erb
<div id="create_proposal">
  <%= form_for (@group.present?) ? [@group, @proposal] : @proposal, validate: true, remote: true do |f| %>
      <%= render partial: 'proposal_types/wizard_steps' %>


      <div class="step root root">
        <% if @group && @group.enable_areas && @group.group_areas.count > 0 && params[:action] == "new" %>
            <p>
              <%= f.label :group_area_id %><br/>
              <%= select("proposal", "group_area_id", @group.group_areas.all.collect { |p| [p.name, p.id] }, {prompt: 'Nessuna area di lavoro'}) %>
            </p>
        <% end %>
        <% if ::Configuration.proposal_categories %>
            <p>
              <%= f.label :proposal_category_id %><br/>
              <%= select("proposal", "proposal_category_id", ProposalCategory.all.collect { |p| [p.description, p.id] }) %>
            </p>
        <% end %>
        <% if params[:action] == "new" %>
            <p>
              <%= f.label :title %> *<br/>
              <%= f.text_field :title, style: "width:300px" %>
            </p>

            <p>
              <%= f.label :interest_borders_tkn %><br/>
              <%= f.text_field 'interest_borders_tkn', "data-pre" => @proposal.interest_borders.to_json %>
            </p>

            <% if ::Configuration::folksonomy %>
                <p>
                  <%= f.label :tags_list %><br/>
                  <%= f.text_field :tags_list %>
                </p>
            <% end %>

            <p>
              <% if @proposal.change_advanced_options %>
                  <%= f.check_box :anonima %>
                  <%= f.label :anonima %><br/>
                  <%= f.check_box :visible_outside %>
                  <%= f.label :visible_outside %><br/>
                  <%= f.check_box :secret_vote %>
                  <%= f.label :secret_vote %><br/>
              <% end %>
            </p>

            <p>
              <% if @group %>
                  <input type="hidden" name="from_group" value="<%= @group.id %>"/>
              <% end %>
              <%= f.hidden_field :private %>
              <%= f.hidden_field :proposal_type_id %>
              <%= f.hidden_field :proposal_votation_type_id %>
            </p>

        <% end %>
      </div>


      <div class="step" id="suggestions">
      </div>

      <div class="step">
        <h4><%= 'Scrivi in maniera adeguata il testo che vuoi portare a sondaggio' %></h4>

        <%= f.fields_for :sections, @text do |s| %>
            <%= s.hidden_field :title %>
            <%= s.hidden_field :seq %>
            <%= s.fields_for :paragraphs, @text.paragraphs.build(seq: 1) do |p| %>
                <p>
                  <%= p.label :content, @text.title %> *<br/>
                  <%= p.text_area :content, rows: 5, style: "width:500px", class: "tinymce" %>
                  <%= p.hidden_field :seq %>
                </p>
            <% end %>
        <% end %>
      </div>

      <div class="step">
            <h4><%= 'Inserisci tutte le possibili scelte del sondaggio' %></h4>

        <%= f.fields_for :solutions, @solution_a do |sol| %>
            <%= sol.hidden_field :seq %>
            <%= sol.fields_for :sections, @solution_a_section do |s| %>
                <%= s.hidden_field :title %>
                <%= s.hidden_field :seq %>
                <%= s.fields_for :paragraphs, @solution_a_section.paragraphs.build(seq: 1) do |p| %>
                    <p>
                      <%= p.label :content, @solution_a_section.title %><br/>
                      <%= p.text_field :content, rows: 5, style: "width:500px" %>
                      <%= p.hidden_field :seq %>
                    </p>
                <% end %>
            <% end %>
        <% end %>

        <%= f.fields_for :solutions, @solution_b do |sol| %>
            <%= sol.hidden_field :seq %>
            <%= sol.fields_for :sections, @solution_b_section do |s| %>
                <%= s.hidden_field :title %>
                <%= s.hidden_field :seq %>
                <%= s.fields_for :paragraphs, @solution_b_section.paragraphs.build(seq: 1) do |p| %>
                    <p>
                      <%= p.label :content, @solution_b_section.title %><br/>
                      <%= p.text_field :content, rows: 5, style: "width:500px" %>
                      <%= p.hidden_field :seq %>
                    </p>
                <% end %>
            <% end %>
        <% end %>

        <%= f.fields_for :solutions, @solution_c do |sol| %>
            <%= sol.hidden_field :seq %>
            <%= sol.fields_for :sections, @solution_c_section do |s| %>
                <%= s.hidden_field :title %>
                <%= s.hidden_field :seq %>
                <%= s.fields_for :paragraphs, @solution_c_section.paragraphs.build(seq: 1) do |p| %>
                    <p>
                      <%= p.label :content, @solution_c_section.title %><br/>
                      <%= p.text_field :content, rows: 5, style: "width:500px" %>
                      <%= p.hidden_field :seq %>
                    </p>
                <% end %>
            <% end %>
        <% end %>


      </div>

      <p>
        <%= render partial: 'fragments/error_messages', locals: {resource: @proposal} %>
        <%= f.submit "Crea il sondaggio", class: 'btn' %>
      </p>
  <% end %>
</div>


<% data = "["
   @proposal.tags_list.split(',').each do |l|
     data += "{\"id\":\""+ l + "\",\"name\":\"" + l + "\"},"
   end
   data += "]"
%>

app/views/proposal_types/_quorum_choice.html.erb
<% if @group %>
  <% @quorum_collection = @group.quorums.active %>
<% else %>
  <% @quorum_collection = Quorum.visible.order('seq nulls last') %>
<% end %>
<%= f.input :quorum_id, as: :select, required: true,
            collection: @quorum_collection.collect { |p| [p.name, p.id, { 'data-description' => p.description,
                                                                          'data-explanation' => p.explanation,
                                                                          'data-time_fixed' => p.time_fixed?,
                                                                          'data-minutes' => p.minutes }] },
            include_blank: t('pages.proposals.new.quorum_prompt'), input_html: { style: 'width: 100%' } %>

<div id="available_quorums_container" title="<%= t('pages.quorums.index.title') %>">
</div>

<div class="clearboth"></div>
<p id="quorum_explanation" class="panel callout" style="display:none;">

</p>

<div class="content" id="choose_votation">
  <div>
  </div>
</div>

app/views/proposal_types/_suggestion_step.html.erb
<h4><%= t('pages.proposals.new.step_2_title') %></h4>
<%= render 'fragments/loading' %>